### ISSUE TITLE
Missing packages?

### ISSUE THREAD

**Issue by whimwich** [sso-aat/libpgplot-perl#1]
This worked as advertised (thanks!), but I also had to install `libdevel-checklib-perl` and `perl-xs-dev`. The latter selected `libperl-dev` instead.

**Comment by jcameron-sso** [comment]
Thanks for testing.

What Linux distribution and release version did this happen on?

My tests were on Ubuntu 22.04 and Debian Sid.  On these, the `apt build-dep` step brings in those packages because of the _Build-Depends_ in [the control file](https://salsa.debian.org/perl-team/modules/packages/libpgplot-perl/-/blob/master/debian/control) of the existing package.  Could you have skipped that step?  If so, I'll make it clearer.

**Comment by whimwich** [comment]
I am testing on Debian _Bullseye_. BTW, we did not have the problem with `pgplot` in _Stretch_. We skipped _Buster_.

I re-followed your instructions on a fresh system, making sure to use `apt build-dep libpgplot-perl`, and had the same issue.

**Comment by jcameron-sso** [comment]
Thanks.  Now that I've tested on Debian _Bullseye_, I get the same.  My package is from Debian _Sid_ and has new dependencies that have to be installed.  I've edited the Wiki page.

**Comment by whimwich** [comment]
Thanks. The instructions work for me now. I am glad that the _Sid_ package works for _Bullseye_.
